name: Sibancompany Backend Deploy CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: Node Packages and Dependencies
        run: |
          echo "Installing Dependencies..."
          npm ci

      - name: Deploy to Staging
        run: |
          echo "Deploying to staging..."
          cat ./scripts/deploy.sh
