name: Sibancompany Backend Test CI/CD

on:
  push:
    branches:
      - main
      - develop
      - hotfix/*
      - release/*
      - feature/*
      - fix/*
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: Node Packages and Dependencies
        run: |
          echo "Installing Dependencies..."
          npm ci

      - name: Prepare .env.test
        run: |
          touch .env.test
          echo "HOST=127.0.0.1" >> .env.test
          echo "DB_PORT=3306" >> .env.test
          echo "DB_USERNAME=root" >> .env.test
          echo "DB_PASSWORD=1234" >> .env.test
          echo "DB_NAME=siban" >> .env.test

      - name: Test API
        run: |
          echo "Running Unit Test..."
          cat .env.test